version: '3'
services:
  pool:
    build:
      context: .
      dockerfile: indy-pool.dockerfile
      args:
        - pool_ip=172.16.0.100
    ports:
      - 9701-9708:9701-9708
    networks:
      services:
        ipv4_address: 172.16.0.100

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles
    networks:
      services:
        ipv4_address: 172.16.0.150

  api:
    build:
      context: .
    container_name: idchain-api
    image: indy-api:latest
    environment:
      - GENESIS_TXN=pool_transactions_genesis.docker-compose
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - pool
    networks:
      services:
        ipv4_address: 172.16.0.200

networks:
  services:
    ipam:
      config:
        - subnet: 172.16.0.0/24
