version: '3'
services:
  pool:
    build:
      context: ..
      dockerfile: ./docker/indy-pool.dockerfile
      args:
        - pool_ip=51.144.36.206
    ports:
      - 9701-9708:9701-9708
    networks:
      indy-network:
        ipv4_address: 51.144.36.206

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles
    networks:
      indy-network:
        ipv4_address: 51.144.36.200
  api:
    build:
      context: ..
      dockerfile: ./docker/api.dockerfile
      args:
        - pool_ip=51.144.36.206
    ports:
      - 8000:8000
    environment:
      - DB_HOST=51.144.36.200
      - APP_HOST=51.144.36.250
    networks:
      indy-network:
        ipv4_address: 51.144.36.250
    depends_on:
      - pool
      - mongodb

  schema-compiler:
    build:
      context: ../schema-api
    container_name: schema-compiler
    ports:
      - 9000:9000
    networks:
      indy-network:
        ipv4_address: 172.16.0.201

networks:
  indy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 51.144.36.0/24
