module.exports = {
    publicPermissions: {
        LOGIN: 'LOGIN',
        AGENT_ENDPOINT: 'AGENT_ENDPOINT',
        REGISTER_A_NEW_USER: 'REGISTER_A_NEW_USER'
    },

    allPermissions: {
        LOGIN: 'LOGIN',
        AGENT_ENDPOINT: 'AGENT_ENDPOINT',
        REGISTER_A_NEW_USER: 'REGISTER_A_NEW_USER',
        GET_LIST_MESSAGES: 'GET_LIST_MESSAGES',
        SEND_MESSAGE: 'SEND_MESSAGE',
        RETRIEVE_MESSAGE: 'RETRIEVE_MESSAGE',
        DELETE_A_MESSAGE: 'DELETE_A_MESSAGE',
        LIST_ALL_CREDENTIALS_OF_SPECIFIC_WALLET: 'LIST_ALL_CREDENTIALS_OF_SPECIFIC_WALLET',
        STORE_A_CREDENTIAL: 'STORE_A_CREDENTIAL',
        ISSUE_CREDENTIAL: 'ISSUE_CREDENTIAL',
        RETRIEVE_A_CREDENTIAL: 'RETRIEVE_A_CREDENTIAL',
        LIST_CREDENTIAL_DEFINITIONS_OF_WALLET: 'LIST_CREDENTIAL_DEFINITIONS_OF_WALLET',
        CREATE_A_CREDENTIAL_DEFINITION: 'CREATE_A_CREDENTIAL_DEFINITION',
        RETRIEVE_A_CREDENTIAL_DEFINITION_FROM_THE_LEDGER: 'RETRIEVE_A_CREDENTIAL_DEFINITION_FROM_THE_LEDGER',
        DELETE_A_CREDENTIAL_DEFINITION: 'DELETE_A_CREDENTIAL_DEFINITION',
        CREATE_A_CREDENTIAL_OFFER: 'CREATE_A_CREDENTIAL_OFFER',
        ACCEPT_CREDENTIAL_OFFER_AND_CREATE_CREDENTIAL_REQUEST: 'ACCEPT_CREDENTIAL_OFFER_AND_CREATE_CREDENTIAL_REQUEST',
        CREATE_A_NEW_CONNECTION_OFFER: 'CREATE_A_NEW_CONNECTION_OFFER',
        ACCEPT_A_CONNECTION_OFFER: 'ACCEPT_A_CONNECTION_OFFER',
        CREATE_A_PROOF_REQUEST: 'CREATE_A_PROOF_REQUEST',
        CREATE_A_PROOF: 'CREATE_A_PROOF',
        CREATE_A_PROOF_VERIFICATION: 'CREATE_A_PROOF_VERIFICATION',
        LIST_SCHEMAS: 'LIST_SCHEMAS',
        CREATE_A_SCHEMA: 'CREATE_A_SCHEMA',
        RETRIEVE_A_SCHEMA: 'RETRIEVE_A_SCHEMA',
        RETRIEVE_A_USER: 'RETRIEVE_A_USER',
        UPDATE_A_USER: 'UPDATE_A_USER',
        DELETE_A_USER: 'DELETE_A_USER',
        LIST_ALL_WALLETS_OF_USER: 'LIST_ALL_WALLETS_OF_USER',
        CREATE_A_NEW_WALLET: 'CREATE_A_NEW_WALLET',
        RETRIEVE_A_WALLET: 'RETRIEVE_A_WALLET',
        DELETE_A_WALLET: 'DELETE_A_WALLET',
        GET_LEDGER_TRANSACTIONS: 'GET_LEDGER_TRANSACTIONS'
    }
};
