const ACTION_PERMISSIONS = {
    ADD_NEW_TRUSTEE: 'ADD_NEW_TRUSTEE',
    BLACKLIST_TRUSTEE: 'BLACKLIST_TRUSTEE',
    ADD_NEW_STEWARD: 'ADD_NEW_STEWARD',
    BLACKLIST_STEWARD: 'BLACKLIST_STEWARD',
    ADD_NEW_TRUST_ANCHOR: 'ADD_NEW_TRUST_ANCHOR',
    BLACKLIST_TRUST_ANCHOR: 'BLACKLIST_TRUST_ANCHOR',
    ADD_NEW_TGB_MEMBER: 'ADD_NEW_TGB_MEMBER',
    BLACKLIST_TGB_MEMBER: 'BLACKLIST_TGB_MEMBER',
    ADD_NEW_IDENTITY_OWNER: 'ADD_NEW_IDENTITY_OWNER',
    ADD_VALIDATOR_NODE: 'ADD_VALIDATOR_NODE',
    BLACKLIST_A_VALIDATOR: 'BLACKLIST_A_VALIDATOR',
    READ_A_VALIDATOR: 'READ_A_VALIDATOR',
    ADD_OBSERVER: 'ADD_OBSERVER',
    BLACKLIST_AN_OBSERVER: 'BLACKLIST_AN_OBSERVER',
    READ_AN_OBSERVER: 'READ_AN_OBSERVER'
};

const TRANSACTION_PERMISSIONS = {
    ROTATE_YOUR_OWN_VERKEYS: 'ROTATE_YOUR_OWN_VERKEYS',
    ROTATE_NODE_KEYS: 'ROTATE_NODE_KEYS',
    ADD_ROLE: 'ADD_ROLE',
    REMOVE_ROLE: 'REMOVE_ROLE',
    NODE: 'NODE',
    NYM: 'NYM',
    ATTRIB: 'ATTRIB',
    SCHEMA: 'SCHEMA',
    GET_SCHEMA: 'GET_SCHEMA',
    DISCLO: 'DISCLO',
    GET_ATTR: 'GET_ATTR',
    GET_NYM: 'GET_NYM',
    GET_TXNS: 'GET_TXNS',
    CLAIM_DEF: 'CLAIM_DEF',
    GET_CLAIM_DEF: 'GET_CLAIM_DEF',
    POOL_UPGRADE: 'POOL_UPGRADE',
    NODE_UPGRADE: 'NODE_UPGRADE'
};

const API_PERMISSIONS = {
    AGENT_ENDPOINT: 'AGENT_ENDPOINT',
    GET_LIST_MESSAGES: 'GET_LIST_MESSAGES',
    SEND_MESSAGE: 'SEND_MESSAGE',
    RETRIEVE_MESSAGE: 'RETRIEVE_MESSAGE',
    DELETE_A_MESSAGE: 'DELETE_A_MESSAGE',
    LIST_ALL_CREDENTIALS_OF_SPECIFIC_WALLET: 'LIST_ALL_CREDENTIALS_OF_SPECIFIC_WALLET',
    STORE_A_CREDENTIAL: 'STORE_A_CREDENTIAL',
    ISSUE_CREDENTIAL: 'ISSUE_CREDENTIAL',
    RETRIEVE_A_CREDENTIAL: 'RETRIEVE_A_CREDENTIAL',
    LIST_CREDENTIAL_DEFINITIONS_OF_WALLET: 'LIST_CREDENTIAL_DEFINITIONS_OF_WALLET',
    CREATE_A_CREDENTIAL_DEFINITION: 'CREATE_A_CREDENTIAL_DEFINITION',
    RETRIEVE_A_CREDENTIAL_DEFINITION_FROM_THE_LEDGER: 'RETRIEVE_A_CREDENTIAL_DEFINITION_FROM_THE_LEDGER',
    DELETE_A_CREDENTIAL_DEFINITION: 'DELETE_A_CREDENTIAL_DEFINITION',
    CREATE_A_CREDENTIAL_OFFER: 'CREATE_A_CREDENTIAL_OFFER',
    ACCEPT_CREDENTIAL_OFFER_AND_CREATE_CREDENTIAL_REQUEST: 'ACCEPT_CREDENTIAL_OFFER_AND_CREATE_CREDENTIAL_REQUEST',
    CREATE_A_NEW_CONNECTION_OFFER: 'CREATE_A_NEW_CONNECTION_OFFER',
    ACCEPT_A_CONNECTION_OFFER: 'ACCEPT_A_CONNECTION_OFFER',
    CREATE_A_PROOF_REQUEST: 'CREATE_A_PROOF_REQUEST',
    CREATE_A_PROOF: 'CREATE_A_PROOF',
    CREATE_A_PROOF_VERIFICATION: 'CREATE_A_PROOF_VERIFICATION',
    LIST_SCHEMAS: 'LIST_SCHEMAS',
    CREATE_A_SCHEMA: 'CREATE_A_SCHEMA',
    RETRIEVE_A_SCHEMA: 'RETRIEVE_A_SCHEMA',
    REGISTER_A_NEW_USER: 'REGISTER_A_NEW_USER',
    RETRIEVE_A_USER: 'RETRIEVE_A_USER',
    UPDATE_A_USER: 'UPDATE_A_USER',
    DELETE_A_USER: 'DELETE_A_USER',
    LIST_ALL_WALLETS_OF_USER: 'LIST_ALL_WALLETS_OF_USER',
    CREATE_A_NEW_WALLET: 'CREATE_A_NEW_WALLET',
    RETRIEVE_A_WALLET: 'RETRIEVE_A_WALLET',
    DELETE_A_WALLET: 'DELETE_A_WALLET',
    GET_LEDGER_TRANSACTIONS: 'GET_LEDGER_TRANSACTIONS',
    LOGIN: 'LOGIN'
};

module.exports = {
    API_PERMISSIONS,
    TRANSACTION_PERMISSIONS,
    ACTION_PERMISSIONS
};
